using System.Text.Json.Serialization;
using CoinGecko.Api.Models.Onchain;
using CoinGecko.Api.Serialization.JsonApi;

namespace CoinGecko.Api.Serialization;

/// <summary>
/// Source-generated JSON context. Every public DTO type used by the library is
/// registered here with a <c>[JsonSerializable]</c> attribute; later tasks add one
/// <c>[JsonSerializable(typeof(NewDto))]</c> entry each. AOT- and trim-safe.
/// </summary>
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.SnakeCaseLower,
    NumberHandling = JsonNumberHandling.AllowReadingFromString,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    Converters = new[] { typeof(UnixSecondsConverter), typeof(TimestampedValueConverter), typeof(CoinOhlcConverter), typeof(SupplyPointConverter), typeof(TolerantDecimalConverter) })]
[JsonSerializable(typeof(CoinGecko.Api.Models.News.NewsArticle))]
[JsonSerializable(typeof(CoinGecko.Api.Models.News.NewsArticle[]))]
[JsonSerializable(typeof(CoinGecko.Api.Models.PingResponse))]
[JsonSerializable(typeof(CoinGecko.Api.Models.TrendingResults))]
[JsonSerializable(typeof(CoinGecko.Api.Models.TrendingCoinItem))]
[JsonSerializable(typeof(CoinGecko.Api.Models.TrendingCoinData))]
[JsonSerializable(typeof(CoinGecko.Api.Models.TrendingNftItem))]
[JsonSerializable(typeof(CoinGecko.Api.Models.TrendingCategoryItem))]
[JsonSerializable(typeof(CoinGecko.Api.Models.SearchResults))]
[JsonSerializable(typeof(CoinGecko.Api.Models.SearchCoinHit))]
[JsonSerializable(typeof(CoinGecko.Api.Models.SearchExchangeHit))]
[JsonSerializable(typeof(CoinGecko.Api.Models.SearchCategoryHit))]
[JsonSerializable(typeof(CoinGecko.Api.Models.SearchNftHit))]
[JsonSerializable(typeof(CoinGecko.Api.Models.CategoryListItem))]
[JsonSerializable(typeof(CoinGecko.Api.Models.CategoryListItem[]))]
[JsonSerializable(typeof(CoinGecko.Api.Models.CoinCategory))]
[JsonSerializable(typeof(CoinGecko.Api.Models.CoinCategory[]))]
[JsonSerializable(typeof(CoinGecko.Api.Models.AssetPlatform))]
[JsonSerializable(typeof(CoinGecko.Api.Models.AssetPlatform[]))]
[JsonSerializable(typeof(CoinGecko.Api.Models.AssetPlatformImage))]
[JsonSerializable(typeof(CoinGecko.Api.Models.TokenList))]
[JsonSerializable(typeof(CoinGecko.Api.Models.TokenListVersion))]
[JsonSerializable(typeof(CoinGecko.Api.Models.TokenListItem))]
[JsonSerializable(typeof(CoinGecko.Api.Models.CompanyTreasury))]
[JsonSerializable(typeof(CoinGecko.Api.Models.Company))]
[JsonSerializable(typeof(CoinGecko.Api.Models.ApiKeyUsage))]
[JsonSerializable(typeof(JsonApiResponse<JsonApiResource>))]
[JsonSerializable(typeof(JsonApiResponse<JsonApiResource[]>))]
[JsonSerializable(typeof(JsonApiResource))]
[JsonSerializable(typeof(JsonApiResource[]))]
[JsonSerializable(typeof(Dictionary<string, object?>))]
[JsonSerializable(typeof(string[]))]
[JsonSerializable(typeof(Dictionary<string, Dictionary<string, decimal?>>))]
[JsonSerializable(typeof(CoinGecko.Api.Models.GlobalMarketEnvelope))]
[JsonSerializable(typeof(CoinGecko.Api.Models.GlobalMarket))]
[JsonSerializable(typeof(CoinGecko.Api.Models.DefiGlobalEnvelope))]
[JsonSerializable(typeof(CoinGecko.Api.Models.DefiGlobal))]
[JsonSerializable(typeof(CoinGecko.Api.Models.GlobalMarketCapPoint))]
[JsonSerializable(typeof(CoinGecko.Api.Resources.GlobalClient.MarketCapChartEnvelope))]
[JsonSerializable(typeof(CoinGecko.Api.Resources.GlobalClient.MarketCapChartData))]
[JsonSerializable(typeof(CoinGecko.Api.Models.Derivative))]
[JsonSerializable(typeof(CoinGecko.Api.Models.Derivative[]))]
[JsonSerializable(typeof(CoinGecko.Api.Models.DerivativeExchange))]
[JsonSerializable(typeof(CoinGecko.Api.Models.DerivativeExchange[]))]
[JsonSerializable(typeof(CoinGecko.Api.Models.DerivativeExchangeDetail))]
[JsonSerializable(typeof(CoinGecko.Api.Models.DerivativeExchangeListItem))]
[JsonSerializable(typeof(CoinGecko.Api.Models.DerivativeExchangeListItem[]))]
[JsonSerializable(typeof(CoinGecko.Api.Models.Exchange))]
[JsonSerializable(typeof(CoinGecko.Api.Models.Exchange[]))]
[JsonSerializable(typeof(CoinGecko.Api.Models.ExchangeListItem))]
[JsonSerializable(typeof(CoinGecko.Api.Models.ExchangeListItem[]))]
[JsonSerializable(typeof(CoinGecko.Api.Models.ExchangeDetail))]
[JsonSerializable(typeof(CoinGecko.Api.Models.Ticker))]
[JsonSerializable(typeof(CoinGecko.Api.Models.Ticker[]))]
[JsonSerializable(typeof(CoinGecko.Api.Models.TickerMarket))]
[JsonSerializable(typeof(CoinGecko.Api.Models.ExchangeTickers))]
[JsonSerializable(typeof(CoinGecko.Api.Models.StatusUpdate))]
[JsonSerializable(typeof(CoinGecko.Api.Models.ExchangeVolumeChartPoint))]
[JsonSerializable(typeof(CoinGecko.Api.Models.ExchangesOptions))]
[JsonSerializable(typeof(CoinGecko.Api.Models.ExchangeTickersOptions))]
[JsonSerializable(typeof(string[][]))]
[JsonSerializable(typeof(CoinGecko.Api.Models.NftListItem))]
[JsonSerializable(typeof(CoinGecko.Api.Models.NftListItem[]))]
[JsonSerializable(typeof(CoinGecko.Api.Models.Nft))]
[JsonSerializable(typeof(CoinGecko.Api.Models.NftMarket))]
[JsonSerializable(typeof(CoinGecko.Api.Models.NftMarket[]))]
[JsonSerializable(typeof(CoinGecko.Api.Models.NftImage))]
[JsonSerializable(typeof(CoinGecko.Api.Models.NftLinks))]
[JsonSerializable(typeof(CoinGecko.Api.Models.NftTicker))]
[JsonSerializable(typeof(CoinGecko.Api.Models.NftTickers))]
[JsonSerializable(typeof(CoinGecko.Api.Models.NftMarketsOptions))]
[JsonSerializable(typeof(CoinGecko.Api.Models.NftMarketChartPoint))]
[JsonSerializable(typeof(CoinGecko.Api.Resources.NftMarketChartRaw))]
[JsonSerializable(typeof(decimal?[][]))]
[JsonSerializable(typeof(CoinGecko.Api.Models.CoinListItem))]
[JsonSerializable(typeof(CoinGecko.Api.Models.CoinListItem[]))]
[JsonSerializable(typeof(CoinGecko.Api.Models.CoinMarket))]
[JsonSerializable(typeof(CoinGecko.Api.Models.CoinMarket[]))]
[JsonSerializable(typeof(CoinGecko.Api.Models.SparklineIn7d))]
[JsonSerializable(typeof(CoinGecko.Api.Models.Coin))]
[JsonSerializable(typeof(CoinGecko.Api.Models.CoinPlatformDetail))]
[JsonSerializable(typeof(CoinGecko.Api.Models.CoinLinks))]
[JsonSerializable(typeof(CoinGecko.Api.Models.CoinReposUrl))]
[JsonSerializable(typeof(CoinGecko.Api.Models.CoinImage))]
[JsonSerializable(typeof(CoinGecko.Api.Models.CoinMarketData))]
[JsonSerializable(typeof(CoinGecko.Api.Models.CoinCommunityData))]
[JsonSerializable(typeof(CoinGecko.Api.Models.CoinDeveloperData))]
[JsonSerializable(typeof(CoinGecko.Api.Models.CoinCodeChanges))]
[JsonSerializable(typeof(CoinGecko.Api.Models.CoinTickers))]
[JsonSerializable(typeof(CoinGecko.Api.Models.CoinHistory))]
[JsonSerializable(typeof(CoinGecko.Api.Models.CoinHistoryMarketData))]
[JsonSerializable(typeof(CoinGecko.Api.Models.CoinPublicInterestStats))]
[JsonSerializable(typeof(CoinGecko.Api.Models.MarketChart))]
[JsonSerializable(typeof(CoinGecko.Api.Models.TimestampedValue))]
[JsonSerializable(typeof(CoinGecko.Api.Models.TimestampedValue[]))]
[JsonSerializable(typeof(CoinGecko.Api.Models.CoinOhlc))]
[JsonSerializable(typeof(CoinGecko.Api.Models.CoinOhlc[]))]
[JsonSerializable(typeof(CoinGecko.Api.Models.SupplyPoint))]
[JsonSerializable(typeof(CoinGecko.Api.Models.SupplyPoint[]))]
[JsonSerializable(typeof(CoinGecko.Api.Models.TopGainersLosers))]
[JsonSerializable(typeof(CoinGecko.Api.Models.NewCoinListing))]
[JsonSerializable(typeof(CoinGecko.Api.Models.NewCoinListing[]))]
[JsonSerializable(typeof(CoinGecko.Api.Models.CoinMarketsOptions))]
[JsonSerializable(typeof(CoinGecko.Api.Models.CoinDetailOptions))]
[JsonSerializable(typeof(CoinGecko.Api.Models.CoinTickersOptions))]
[JsonSerializable(typeof(JsonApiResponse<Network[]>))]
[JsonSerializable(typeof(JsonApiResponse<Network>))]
[JsonSerializable(typeof(JsonApiResponse<Dex[]>))]
[JsonSerializable(typeof(JsonApiResponse<Pool>))]
[JsonSerializable(typeof(JsonApiResponse<Pool[]>))]
[JsonSerializable(typeof(JsonApiResponse<OnchainTrade[]>))]
[JsonSerializable(typeof(JsonApiResponse<OnchainOhlcvResource>))]
[JsonSerializable(typeof(JsonApiResponse<PoolInfo>))]
[JsonSerializable(typeof(Network))]
[JsonSerializable(typeof(Network[]))]
[JsonSerializable(typeof(NetworkAttributes))]
[JsonSerializable(typeof(Dex))]
[JsonSerializable(typeof(Dex[]))]
[JsonSerializable(typeof(DexAttributes))]
[JsonSerializable(typeof(Pool))]
[JsonSerializable(typeof(Pool[]))]
[JsonSerializable(typeof(PoolAttributes))]
[JsonSerializable(typeof(PoolRelationships))]
[JsonSerializable(typeof(OnchainTrade))]
[JsonSerializable(typeof(OnchainTrade[]))]
[JsonSerializable(typeof(OnchainTradeAttributes))]
[JsonSerializable(typeof(OnchainOhlcvResource))]
[JsonSerializable(typeof(OnchainOhlcvAttributes))]
[JsonSerializable(typeof(PoolInfo))]
[JsonSerializable(typeof(OnchainTokenMetadata))]
[JsonSerializable(typeof(IReadOnlyDictionary<string, decimal?>))]
[JsonSerializable(typeof(IReadOnlyDictionary<string, long?>))]
[JsonSerializable(typeof(IReadOnlyDictionary<string, IReadOnlyDictionary<string, long?>>))]
[JsonSerializable(typeof(JsonApiResponse<OnchainToken>))]
[JsonSerializable(typeof(JsonApiResponse<OnchainToken[]>))]
[JsonSerializable(typeof(JsonApiResponse<OnchainTokenInfo>))]
[JsonSerializable(typeof(JsonApiResponse<OnchainTokenInfo[]>))]
[JsonSerializable(typeof(JsonApiResponse<OnchainTopTrader[]>))]
[JsonSerializable(typeof(JsonApiResponse<OnchainTopHolders>))]
[JsonSerializable(typeof(JsonApiResponse<OnchainHoldersChart>))]
[JsonSerializable(typeof(JsonApiResponse<OnchainCategory[]>))]
[JsonSerializable(typeof(JsonApiResponse<OnchainTokenPrices>))]
[JsonSerializable(typeof(OnchainToken))]
[JsonSerializable(typeof(OnchainToken[]))]
[JsonSerializable(typeof(OnchainTokenAttributes))]
[JsonSerializable(typeof(OnchainTokenRelationships))]
[JsonSerializable(typeof(OnchainTokenInfo))]
[JsonSerializable(typeof(OnchainTokenInfoAttributes))]
[JsonSerializable(typeof(OnchainTopTrader))]
[JsonSerializable(typeof(OnchainTopHolders))]
[JsonSerializable(typeof(OnchainTopHoldersAttributes))]
[JsonSerializable(typeof(OnchainTopHolder))]
[JsonSerializable(typeof(OnchainTopHolder[]))]
[JsonSerializable(typeof(OnchainHoldersChart))]
[JsonSerializable(typeof(OnchainHoldersChartAttributes))]
[JsonSerializable(typeof(OnchainCategory))]
[JsonSerializable(typeof(OnchainCategory[]))]
[JsonSerializable(typeof(OnchainCategoryAttributes))]
[JsonSerializable(typeof(OnchainTokenPrices))]
[JsonSerializable(typeof(OnchainTokenPricesAttributes))]
internal sealed partial class CoinGeckoJsonContext : JsonSerializerContext
{
}
